name: Infrastructure Security Scan (Checkov)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run Checkov Scan
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          # This scans the entire directory
          directory: .
          # This ensures it doesn't fail your build immediately while we tune it
          soft_fail: true 
          framework: all
          output_format: cli,sarif
          output_file_path: console,results.sarif

      - name: Upload SARIF Results
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: results.sarif